---
# Playbook to create a loopback interface and assign an IP address to it on CSR1kv router

# Playbook metadata
- name: CREATE LOOPBACK INTERFACE  # Descriptive name of the playbook
  hosts: iosxe_reserved  # Target hosts on which the tasks will be executed
  gather_facts: False  # Skips gathering facts about the hosts
  connection: local  # Establishes a local connection to the Ansible controller
  become: yes  # Enables privilege escalation for tasks requiring root privileges
  become_method: enable  # Specifies the method to become privileged user

  tasks:
    # Task to create the loopback interface
    - name: Creating loopback 
      ios_interface:  # Module to manage layer 2 and layer 3 interfaces on IOS devices
        name: Loopback100  # Name of the loopback interface to be created
        enabled: True  # Specifies whether the interface is administratively enabled
        description: Loopback interface 100 created with Ansible  # Description of the interface

    # Task to assign an IP address to the loopback interface
    - name: Assign IPv4 to loopback
      ios_l3_interface:  # Module to manage layer 3 interfaces on IOS devices
        name: Loopback100  # Name of the loopback interface to which IP will be assigned
        ipv4: 10.0.15.100/32  # IPv4 address and subnet mask in CIDR notation

    # Task to assign an IP address to the loopback interface
    - name: Assign IPv6 (1) to loopback
      ios_l3_interface:  # Module to manage layer 3 interfaces on IOS devices
        name: Loopback100  # Name of the loopback interface to which IP will be assigned
        ipv6: 2001:db8:1::101/64  # IPv4 address and subnet mask in CIDR notation

    # Task to assign an IP address to the loopback interface
    - name: Assign IPv6 (2) to loopback
      ios_l3_interface:  # Module to manage layer 3 interfaces on IOS devices
        name: Loopback100  # Name of the loopback interface to which IP will be assigned
        ipv6: 2001:db8:2::102/64 # IPv4 address and subnet mask in CIDR notation

    