---
- name: AUTOMATIC BACKUP OF RUNNING-CONFIG
  hosts: reserved
  gather_facts: false
  connection: local
 
  tasks:
   - name: DISPLAYING THE RUNNING-CONFIG
     ios_command:
       commands:
         - show running-config  
     register: config
 
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "/home/devasc/DevascExperiments/network_programmability/IaCExperiments/Sshow_run_{{inventory_hostname }}.txt"

